http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  security:
    host: localhost
    paths: '/v1/auth/*'
  accounts:
    host: localhost
    paths: 'v1/accounts/*'
  products:
    host: localhost
    paths: 'v1/products/*'
  invoiceCustomers:
    host: localhost
    paths: '/v1/customers/invoice/*'
  paymentsCore:
    host: localhost
    paths: '/v1/payments/core/*'
  checkouts:
    host: localhost
    paths: '/v1/checkouts/*'
  cybersource:
    host: localhost
    paths: '/v1/cybersource/*'
  tokenizer:
    host: localhost
    paths: '/v1/tokenizer/*'
  paymentCustomers:
    host: localhost
    paths: '/v1/customers/payment/*'
  orders:
    host: localhost
    paths: '/v1/orders/*'
  payments:
    host: localhost
    paths: '/v1/payments/*'
serviceEndpoints:
  securityService:
    url: 'http://localhost:9089'
  accountsService:
    url: 'http://localhost:9096'
  productsService:
    url: 'http://localhost:9097'
  invoiceCustomersService:
    url: 'http://localhost:9098'
  paymentsCoreService:
    url: 'http://localhost:9095'
  checkoutsService:
    url: 'http://localhost:9099'
  cybersourceService:
    url: 'http://localhost:9093'
  tokenizerService:
    url: 'http://localhost:9094'
  paymentCustomersService:
    url: 'http://localhost:9086'
  ordersService:
    url: 'http://localhost:9088'
  paymentsService:
    url: 'http://localhost:9087'
pipelines:
  securityPipeline:
    apiEndpoints:
      - security
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD, GET, PUT, POST, PATCH, DELETE'
              Access-Control-Allow-Headers: true
      - proxy:
          - action:
              serviceEndpoint: securityService
              changeOrigin: true
  accountsPipeline:
    apiEndpoints:
      - accounts
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD, GET, PUT, POST, PATCH, DELETE'
              Access-Control-Allow-Headers: true
      - proxy:
          - action:
              serviceEndpoint: accountsService
              changeOrigin: true
  productsPipeline:
    apiEndpoints:
      - products
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD, GET, PUT, POST, PATCH, DELETE'
              Access-Control-Allow-Headers: true
      - proxy:
          - action:
              serviceEndpoint: productsService
              changeOrigin: true
  invoiceCustomersPipeline:
    apiEndpoints:
      - invoiceCustomers
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD, GET, PUT, POST, PATCH, DELETE'
              Access-Control-Allow-Headers: true
      - proxy:
          - action:
              serviceEndpoint: invoiceCustomersService
              changeOrigin: true
  paymentsCorePipeline:
    apiEndpoints:
      - paymentsCore
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'POST'
              Access-Control-Allow-Headers: true
      - proxy:
          - action:
              serviceEndpoint: paymentsCoreService
              changeOrigin: true
  checkoutsPipeline:
    apiEndpoints:
      - checkouts
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD, GET, PUT, POST, PATCH, DELETE'
              Access-Control-Allow-Headers: true
      - proxy:
          - action:
              serviceEndpoint: checkoutsService
              changeOrigin: true
  cybersourcePipeline:
    apiEndpoints:
      - cybersource
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'POST, GET'
              Access-Control-Allow-Headers: true
      - proxy:
          - action:
              serviceEndpoint: cybersourceService
              changeOrigin: true
  tokenizerPipeline:
    apiEndpoints:
      - tokenizer
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'POST'
              Access-Control-Allow-Headers: true
      - proxy:
          - action:
              serviceEndpoint: tokenizerService
              changeOrigin: true
  paymentCustomersPipeline:
    apiEndpoints:
      - paymentCustomers
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD, GET, PUT, POST, PATCH, DELETE'
              Access-Control-Allow-Headers: true
      - proxy:
          - action:
              serviceEndpoint: paymentCustomersService
              changeOrigin: true
  ordersPipeline:
    apiEndpoints:
      - orders
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD, GET, PUT, POST, PATCH, DELETE'
              Access-Control-Allow-Headers: true
      - proxy:
          - action:
              serviceEndpoint: ordersService
              changeOrigin: true
  paymentsPipeline:
    apiEndpoints:
      - payments
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET'
              Access-Control-Allow-Headers: true
      - proxy:
          - action:
              serviceEndpoint: paymentsService
              changeOrigin: true
policies:
  - cors
  - proxy

